### ISSUE TITLE
Google+ Setup

### ISSUE THREAD

**Issue by enricobertelli** [RebelTechnology/FortRebel#59]
Please send Pic for logo (banner style and thumbnail).
Short motto (50 characters)

**Comment by pingdynasty** [comment]
Logo in SVG
https://drive.google.com/file/d/0BzlB8MFUox37Z1NLLWRrZHJCTDg/view?usp=sharing

**Comment by pingdynasty** [comment]
This is the quirp I wrote for the Barcelona meeting:
Rebel Technology is a tech collective based in London that has been creating innovative music electronics since 2009. They are the makers of several popular and unique Eurorack modules including Stoicheia: the Euclidean sequencer, Bit Reactor: a low-fi bit crusher and downsampler, and Chronos: tap tempo and LFO. Rebel Technology also ran the successful Kickstarter campaign for the OWL, a high-performance, fully programmable fx pedal, which is now coming out in modular format.
All their products are Open Source and Open Hardware, and several models are available as DIY kits. Hackers, modders, benders and builders - Rebel Technology salute you!

**Comment by enricobertelli** [comment]
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66336848-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by enricobertelli** [comment]
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66336848-2', 'auto');
  ga('send', 'pageview');

</script>
```

This is the script for the Hoxton OWL

**Comment by pingdynasty** [comment]
https://github.com/pingdynasty/OwlServer/issues/84

**Comment by enricobertelli** [comment]
Google+ is now alive and kicking. When you have time, you should add people to the circles and start posting some stuff there.
Thanks!
Enrico
