### ISSUE TITLE
Pack for Tilburg

### ISSUE THREAD

**Issue by ghost** [RebelTechnology/FortRebel#72]
# Workshop
- irons
- snippers
- solder wire
- dmm
- components
- panels
- pcbs
- knobs
- test rig
- programmer
# Stall
- demo rig
- demo OWL pedal
- mini case
- speakers
- headphones
- headphone mixer
- tablet and mount
- laptop
- display board/banner
- marker pen
- post it notes
- blank paper sheets
- stock to sell
- t-shirts
- leaflets
# General
- camera
- business cards
- euro power adapters
- 4way sockets
- printed trade pricelists
# Prepare
- leaflet: what is the OWL pedal/modular
- leaflet: products and prices
- leaflet: workshops
- banner
- how to take payment: paypal & cash?
- contact form

**Comment by pingdynasty** [comment]
todo:
- download videos and flyers onto tablet and laptop
- test vlc playlist
- clean up and brand tablet and laptop
- finish flyers - done
- sort through t-shirts and fold - done
- pack t-shirts
- Modular Ping Pong 
- buy Sennheiser headphones hd201 - done
- prepare order form
- prepare template email receipt / invoice
- get 5 euro notes
- prepare discount notice

```
incubate special
15% off all products purchased during DIY Synth Convention
```
- print trade pricelists

tech:
- finish OSM prototype firmware
- sort out Volty
- assemble subracks

**Comment by pingdynasty** [comment]
Hans van Dorssen hans@incubate.org

Well i had to reshape the tables a bit due to space inside the location.
To fit in enough stands
so sizes now are all still 1m wide
Length.

8 tables length 1.80x2
2 tables trapezium length 1m to 2m
2 tables trapezium length 2m to 2m
6 tables rhombus 1.50 x 1.50
4 tables length 1.50 x 2m
But connected to each other to make shifting space possible.

it's like the drawing  hope it makes sense:)
Hope U are ok with this!

Also attached train tickets for Ur self and Patrick.
Check in on-line for e-tickets(just reminding in case).
And take print out ticket for train with U to get in train.
My number is 0031641516479 in case of anything to help out or when u arrive.
See u on Wednesday!!
